name: cacophony
synopsis: A library implementing the Noise protocol.
version: 0.10.0
license: PublicDomain
license-file: LICENSE
maintainer: John Galt <jgalt@centromere.net>
category: Cryptography
github: centromere/cacophony
ghc-options: -Wall
description: |
  This library implements the <https://noiseprotocol.org Noise> protocol.
extra-source-files:
  - .travis.yml
  - README.md
  - changelog.md
  - LICENSE
  - stack.yaml
  - package.yaml
  - tests/.hlint
  - tools/convert_vectors.py
  - tools/run_benchmarks.sh
  - tools/vector_template.jinja
  - vectors/cacophony.txt

flags:
  hlint:
    description: Build hlint test
    default: False
    manual: False

  vectors:
    description: Build vector test
    default: False
    manual: False

  build-examples:
    description: Build example executables
    default: False
    manual: True

library:
  source-dirs: src
  dependencies:
    - base >= 4.9 && < 4.10
    - bytestring
    - cryptonite
    - exceptions
    - free
    - lens
    - memory
    - monad-coroutine
    - mtl
    - safe-exceptions
    - transformers

  exposed-modules:
    - Crypto.Noise
    - Crypto.Noise.Cipher
    - Crypto.Noise.Cipher.AESGCM
    - Crypto.Noise.Cipher.ChaChaPoly1305
    - Crypto.Noise.DH
    - Crypto.Noise.DH.Curve25519
    - Crypto.Noise.DH.Curve448
    - Crypto.Noise.Exception
    - Crypto.Noise.HandshakePatterns
    - Crypto.Noise.Hash
    - Crypto.Noise.Hash.BLAKE2b
    - Crypto.Noise.Hash.BLAKE2s
    - Crypto.Noise.Hash.SHA256
    - Crypto.Noise.Hash.SHA512
    - Crypto.Noise.Internal.CipherState
    - Crypto.Noise.Internal.Handshake.Interpreter
    - Crypto.Noise.Internal.Handshake.Pattern
    - Crypto.Noise.Internal.Handshake.State
    - Crypto.Noise.Internal.Handshake.Validation
    - Crypto.Noise.Internal.NoiseState
    - Crypto.Noise.Internal.SymmetricState
    - Crypto.Noise.Validation

  default-extensions:
    - OverloadedStrings

tests:
  hlint:
    main: hlint.hs
    source-dirs: tests/hlint
    when:
      - condition: 'flag(hlint)'
        then:
          dependencies:
            - base >= 4.9 && < 4.10
            - hlint
        else:
          buildable: False

    ghc-options:
      - -O2
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

  vectors:
    main: Main.hs
    source-dirs: tests/vectors
    when:
      - condition: 'flag(vectors)'
        then:
          dependencies:
            - aeson
            - attoparsec
            - base >= 4.9 && < 4.10
            - base16-bytestring
            - bytestring
            - cacophony
            - directory
            - lens
            - memory
            - text
        else:
          buildable: False

    ghc-options:
      - -O2
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

    default-extensions:
      - OverloadedStrings

benchmarks:
  bench:
    main: bench.hs
    source-dirs: benchmarks
    dependencies:
      - async
      - base >= 4.9 && < 4.10
      - base16-bytestring
      - bytestring
      - cacophony
      - criterion
      - deepseq
      - lens
      - memory

    ghc-options:
      - -O2
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

    default-extensions:
      - OverloadedStrings

executables:
  echo-server:
    source-dirs: examples/echo-server
    main: Main.hs
    when:
      - condition: 'flag(build-examples)'
        then:
          dependencies:
            - attoparsec
            - auto-update
            - base
            - base64-bytestring
            - bytestring
            - cacophony
            - cryptonite
            - fast-logger
            - memory
            - network
            - network-simple
            - unix
            - unix-time
        else:
          buildable: False

    ghc-options:
      - -O2
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

    default-extensions:
      - OverloadedStrings

  echo-client:
    source-dirs: examples/echo-client
    main: Main.hs
    when:
      - condition: 'flag(build-examples)'
        then:
          dependencies:
            - attoparsec
            - base
            - base64-bytestring
            - bytestring
            - cacophony
            - haskeline
            - memory
            - network
            - network-simple
            - unix
        else:
          buildable: False

    ghc-options:
      - -O2
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

    default-extensions:
      - OverloadedStrings
